improve database retrieval and add icon/cover
5am-code/laravel-notion-api pull request #36
Opened 2021-09-19 18:52 UTC by johguentner

improve database retrieval and add icon/cover:
- replace notion-api-docs link with updated page (Databases)
- add icon, iconType, cover, coverType to Database and Page with according extraction of different cover- and icon-types
- add database-notion-url retrieval to database
- add raw-information-retrieval to database-retrieval (add as empty properties with according information to property-key and options)
- add retrieval of available options to MultiSelect and Select during database retrieval
- don't retrieve rollup and formula if type-value is not given
- don't retrieve created_time and last_edited_time if retrieved content is null
- fix missing id's and wrong options-field (array in array) within response-json-files
- mark databases->all() as deprecated

2021-09-19 19:00 UTC, mechelon requested changes

2021-09-19 19:00 UTC, mechelon commented on src/Entities/Properties/Rollup.php
> +        if(array_key_exists('type', $this->rawContent))
Arr::exists?

2021-09-24 09:29 UTC, johguentner commented on src/Entities/Properties/Rollup.php
> +        if(array_key_exists('type', $this->rawContent))
✔️ Done

2021-09-24 09:31 UTC, johguentner commented on src/Entities/Properties/MultiSelect.php
> +        if(array_key_exists('options', $this->rawContent)){
✔️ Done

2021-09-24 09:31 UTC, johguentner commented on src/Entities/Properties/LastEditedTime.php
> +            if ($this->rawContent != null) {
✔️ Done

2021-09-24 09:31 UTC, johguentner commented on src/Entities/Properties/Formula.php
> +            if ($this->formulaType == 'string' || $this->formulaType == 'number' || $this->formulaType == 'boolean') {
✔️ Done

2021-09-24 09:31 UTC, johguentner commented on src/Entities/Properties/Formula.php
> +        if (array_key_exists('type', $this->rawContent)) {
✔️ Done

2021-09-24 09:31 UTC, johguentner commented on src/Entities/Database.php
> +    public function getProperties(): Collection
✔️ Done

2021-09-24 10:26 UTC, mechelon approved these changes

2021-09-25 19:56 UTC, merged